"""empty message

Revision ID: 6ac0c83e9c60
Revises: 21ee87e954ca
Create Date: 2021-04-24 01:54:54.549082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac0c83e9c60'
down_revision = '21ee87e954ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('perfil_producto_id_perfil_fkey', 'perfil_producto', type_='foreignkey')
    op.create_foreign_key(None, 'perfil_producto', 'perfil', ['id_perfil'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'perfil_producto', type_='foreignkey')
    op.create_foreign_key('perfil_producto_id_perfil_fkey', 'perfil_producto', 'user', ['id_perfil'], ['id'])
    # ### end Alembic commands ###
